// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: osdd/recipes/context.proto

package recipes

import (
	osdd "github.com/opensdd/osdd-api/clients/go/osdd"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Context enumerates files that should be injected into the agent workspace.
type Context struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*ContextEntry       `protobuf:"bytes,1,rep,name=entries,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_osdd_recipes_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_recipes_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Context) GetEntries() []*ContextEntry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *Context) SetEntries(v []*ContextEntry) {
	x.xxx_hidden_Entries = &v
}

type Context_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Ordered list of entries that will be materialized.
	Entries []*ContextEntry
}

func (b0 Context_builder) Build() *Context {
	m0 := &Context{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

// ContextEntry associates a logical path with its content source.
type ContextEntry struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path   string                 `protobuf:"bytes,1,opt,name=path,proto3"`
	xxx_hidden_From   *ContextFrom           `protobuf:"bytes,2,opt,name=from,proto3"`
	xxx_hidden_Filter *osdd.EntryFilter      `protobuf:"bytes,3,opt,name=filter,proto3,oneof"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContextEntry) Reset() {
	*x = ContextEntry{}
	mi := &file_osdd_recipes_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextEntry) ProtoMessage() {}

func (x *ContextEntry) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_recipes_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContextEntry) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *ContextEntry) GetFrom() *ContextFrom {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *ContextEntry) GetFilter() *osdd.EntryFilter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *ContextEntry) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *ContextEntry) SetFrom(v *ContextFrom) {
	x.xxx_hidden_From = v
}

func (x *ContextEntry) SetFilter(v *osdd.EntryFilter) {
	x.xxx_hidden_Filter = v
}

func (x *ContextEntry) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *ContextEntry) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *ContextEntry) ClearFrom() {
	x.xxx_hidden_From = nil
}

func (x *ContextEntry) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

type ContextEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Destination path relative to the workspace root.
	Path string
	// Definition of where the content should be sourced from.
	From *ContextFrom
	// Optional filter limiting the entry to specific IDE integrations.
	Filter *osdd.EntryFilter
}

func (b0 ContextEntry_builder) Build() *ContextEntry {
	m0 := &ContextEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_From = b.From
	x.xxx_hidden_Filter = b.Filter
	return m0
}

// ContextFrom lists the supported sources for populating a context entry.
type ContextFrom struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type isContextFrom_Type     `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContextFrom) Reset() {
	*x = ContextFrom{}
	mi := &file_osdd_recipes_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextFrom) ProtoMessage() {}

func (x *ContextFrom) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_recipes_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContextFrom) GetCombined() *CombinedContextSource {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_Combined); ok {
			return x.Combined
		}
	}
	return nil
}

func (x *ContextFrom) GetGithub() *osdd.GitReference {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_Github); ok {
			return x.Github
		}
	}
	return nil
}

func (x *ContextFrom) GetCmd() *osdd.Exec {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_Cmd); ok {
			return x.Cmd
		}
	}
	return nil
}

func (x *ContextFrom) GetText() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ContextFrom) GetPrefetchId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_PrefetchId); ok {
			return x.PrefetchId
		}
	}
	return ""
}

func (x *ContextFrom) GetUserInput() *UserInputContextSource {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_UserInput); ok {
			return x.UserInput
		}
	}
	return nil
}

func (x *ContextFrom) GetLocalFile() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_LocalFile); ok {
			return x.LocalFile
		}
	}
	return ""
}

func (x *ContextFrom) GetGitRepo() *osdd.GitRepository {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_GitRepo); ok {
			return x.GitRepo
		}
	}
	return nil
}

func (x *ContextFrom) GetJiraIssues() *JiraIssuesSource {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_JiraIssues); ok {
			return x.JiraIssues
		}
	}
	return nil
}

func (x *ContextFrom) GetLinearIssues() *LinearIssuesSource {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_LinearIssues); ok {
			return x.LinearIssues
		}
	}
	return nil
}

func (x *ContextFrom) GetGitHistory() *GitHistorySource {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*contextFrom_GitHistory); ok {
			return x.GitHistory
		}
	}
	return nil
}

func (x *ContextFrom) SetCombined(v *CombinedContextSource) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &contextFrom_Combined{v}
}

func (x *ContextFrom) SetGithub(v *osdd.GitReference) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &contextFrom_Github{v}
}

func (x *ContextFrom) SetCmd(v *osdd.Exec) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &contextFrom_Cmd{v}
}

func (x *ContextFrom) SetText(v string) {
	x.xxx_hidden_Type = &contextFrom_Text{v}
}

func (x *ContextFrom) SetPrefetchId(v string) {
	x.xxx_hidden_Type = &contextFrom_PrefetchId{v}
}

func (x *ContextFrom) SetUserInput(v *UserInputContextSource) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &contextFrom_UserInput{v}
}

func (x *ContextFrom) SetLocalFile(v string) {
	x.xxx_hidden_Type = &contextFrom_LocalFile{v}
}

func (x *ContextFrom) SetGitRepo(v *osdd.GitRepository) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &contextFrom_GitRepo{v}
}

func (x *ContextFrom) SetJiraIssues(v *JiraIssuesSource) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &contextFrom_JiraIssues{v}
}

func (x *ContextFrom) SetLinearIssues(v *LinearIssuesSource) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &contextFrom_LinearIssues{v}
}

func (x *ContextFrom) SetGitHistory(v *GitHistorySource) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &contextFrom_GitHistory{v}
}

func (x *ContextFrom) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *ContextFrom) HasCombined() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_Combined)
	return ok
}

func (x *ContextFrom) HasGithub() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_Github)
	return ok
}

func (x *ContextFrom) HasCmd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_Cmd)
	return ok
}

func (x *ContextFrom) HasText() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_Text)
	return ok
}

func (x *ContextFrom) HasPrefetchId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_PrefetchId)
	return ok
}

func (x *ContextFrom) HasUserInput() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_UserInput)
	return ok
}

func (x *ContextFrom) HasLocalFile() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_LocalFile)
	return ok
}

func (x *ContextFrom) HasGitRepo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_GitRepo)
	return ok
}

func (x *ContextFrom) HasJiraIssues() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_JiraIssues)
	return ok
}

func (x *ContextFrom) HasLinearIssues() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_LinearIssues)
	return ok
}

func (x *ContextFrom) HasGitHistory() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*contextFrom_GitHistory)
	return ok
}

func (x *ContextFrom) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *ContextFrom) ClearCombined() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_Combined); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ContextFrom) ClearGithub() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_Github); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ContextFrom) ClearCmd() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_Cmd); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ContextFrom) ClearText() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_Text); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ContextFrom) ClearPrefetchId() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_PrefetchId); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ContextFrom) ClearUserInput() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_UserInput); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ContextFrom) ClearLocalFile() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_LocalFile); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ContextFrom) ClearGitRepo() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_GitRepo); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ContextFrom) ClearJiraIssues() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_JiraIssues); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ContextFrom) ClearLinearIssues() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_LinearIssues); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *ContextFrom) ClearGitHistory() {
	if _, ok := x.xxx_hidden_Type.(*contextFrom_GitHistory); ok {
		x.xxx_hidden_Type = nil
	}
}

const ContextFrom_Type_not_set_case case_ContextFrom_Type = 0
const ContextFrom_Combined_case case_ContextFrom_Type = 100
const ContextFrom_Github_case case_ContextFrom_Type = 101
const ContextFrom_Cmd_case case_ContextFrom_Type = 102
const ContextFrom_Text_case case_ContextFrom_Type = 103
const ContextFrom_PrefetchId_case case_ContextFrom_Type = 104
const ContextFrom_UserInput_case case_ContextFrom_Type = 105
const ContextFrom_LocalFile_case case_ContextFrom_Type = 106
const ContextFrom_GitRepo_case case_ContextFrom_Type = 107
const ContextFrom_JiraIssues_case case_ContextFrom_Type = 108
const ContextFrom_LinearIssues_case case_ContextFrom_Type = 109
const ContextFrom_GitHistory_case case_ContextFrom_Type = 110

func (x *ContextFrom) WhichType() case_ContextFrom_Type {
	if x == nil {
		return ContextFrom_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *contextFrom_Combined:
		return ContextFrom_Combined_case
	case *contextFrom_Github:
		return ContextFrom_Github_case
	case *contextFrom_Cmd:
		return ContextFrom_Cmd_case
	case *contextFrom_Text:
		return ContextFrom_Text_case
	case *contextFrom_PrefetchId:
		return ContextFrom_PrefetchId_case
	case *contextFrom_UserInput:
		return ContextFrom_UserInput_case
	case *contextFrom_LocalFile:
		return ContextFrom_LocalFile_case
	case *contextFrom_GitRepo:
		return ContextFrom_GitRepo_case
	case *contextFrom_JiraIssues:
		return ContextFrom_JiraIssues_case
	case *contextFrom_LinearIssues:
		return ContextFrom_LinearIssues_case
	case *contextFrom_GitHistory:
		return ContextFrom_GitHistory_case
	default:
		return ContextFrom_Type_not_set_case
	}
}

type ContextFrom_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Chosen source type used to resolve the entry.

	// Fields of oneof xxx_hidden_Type:
	// Combine multiple sub-sources together.
	Combined *CombinedContextSource
	// Fetch content from a Git repository.
	Github *osdd.GitReference
	// Execute a command and capture its output.
	Cmd *osdd.Exec
	// Inline text content embedded in the recipe.
	Text *string
	// Reference to a blob returned by PrefetchResult.
	PrefetchId *string
	// Prompt user for the content at runtime.
	UserInput *UserInputContextSource
	// Local file should be mostly used for tests. If the provided path is relative, then it will be relative to the
	// current working directory.
	LocalFile *string
	// Git repository that needs to be checked out in its entirety.
	GitRepo      *osdd.GitRepository
	JiraIssues   *JiraIssuesSource
	LinearIssues *LinearIssuesSource
	GitHistory   *GitHistorySource
	// -- end of xxx_hidden_Type
}

func (b0 ContextFrom_builder) Build() *ContextFrom {
	m0 := &ContextFrom{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Combined != nil {
		x.xxx_hidden_Type = &contextFrom_Combined{b.Combined}
	}
	if b.Github != nil {
		x.xxx_hidden_Type = &contextFrom_Github{b.Github}
	}
	if b.Cmd != nil {
		x.xxx_hidden_Type = &contextFrom_Cmd{b.Cmd}
	}
	if b.Text != nil {
		x.xxx_hidden_Type = &contextFrom_Text{*b.Text}
	}
	if b.PrefetchId != nil {
		x.xxx_hidden_Type = &contextFrom_PrefetchId{*b.PrefetchId}
	}
	if b.UserInput != nil {
		x.xxx_hidden_Type = &contextFrom_UserInput{b.UserInput}
	}
	if b.LocalFile != nil {
		x.xxx_hidden_Type = &contextFrom_LocalFile{*b.LocalFile}
	}
	if b.GitRepo != nil {
		x.xxx_hidden_Type = &contextFrom_GitRepo{b.GitRepo}
	}
	if b.JiraIssues != nil {
		x.xxx_hidden_Type = &contextFrom_JiraIssues{b.JiraIssues}
	}
	if b.LinearIssues != nil {
		x.xxx_hidden_Type = &contextFrom_LinearIssues{b.LinearIssues}
	}
	if b.GitHistory != nil {
		x.xxx_hidden_Type = &contextFrom_GitHistory{b.GitHistory}
	}
	return m0
}

type case_ContextFrom_Type protoreflect.FieldNumber

func (x case_ContextFrom_Type) String() string {
	md := file_osdd_recipes_context_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isContextFrom_Type interface {
	isContextFrom_Type()
}

type contextFrom_Combined struct {
	// Combine multiple sub-sources together.
	Combined *CombinedContextSource `protobuf:"bytes,100,opt,name=combined,proto3,oneof"`
}

type contextFrom_Github struct {
	// Fetch content from a Git repository.
	Github *osdd.GitReference `protobuf:"bytes,101,opt,name=github,proto3,oneof"`
}

type contextFrom_Cmd struct {
	// Execute a command and capture its output.
	Cmd *osdd.Exec `protobuf:"bytes,102,opt,name=cmd,proto3,oneof"`
}

type contextFrom_Text struct {
	// Inline text content embedded in the recipe.
	Text string `protobuf:"bytes,103,opt,name=text,proto3,oneof"`
}

type contextFrom_PrefetchId struct {
	// Reference to a blob returned by PrefetchResult.
	PrefetchId string `protobuf:"bytes,104,opt,name=prefetch_id,json=prefetchId,proto3,oneof"`
}

type contextFrom_UserInput struct {
	// Prompt user for the content at runtime.
	UserInput *UserInputContextSource `protobuf:"bytes,105,opt,name=user_input,json=userInput,proto3,oneof"`
}

type contextFrom_LocalFile struct {
	// Local file should be mostly used for tests. If the provided path is relative, then it will be relative to the
	// current working directory.
	LocalFile string `protobuf:"bytes,106,opt,name=local_file,json=localFile,proto3,oneof"`
}

type contextFrom_GitRepo struct {
	// Git repository that needs to be checked out in its entirety.
	GitRepo *osdd.GitRepository `protobuf:"bytes,107,opt,name=git_repo,json=gitRepo,proto3,oneof"`
}

type contextFrom_JiraIssues struct {
	JiraIssues *JiraIssuesSource `protobuf:"bytes,108,opt,name=jira_issues,json=jiraIssues,proto3,oneof"`
}

type contextFrom_LinearIssues struct {
	LinearIssues *LinearIssuesSource `protobuf:"bytes,109,opt,name=linear_issues,json=linearIssues,proto3,oneof"`
}

type contextFrom_GitHistory struct {
	GitHistory *GitHistorySource `protobuf:"bytes,110,opt,name=git_history,json=gitHistory,proto3,oneof"`
}

func (*contextFrom_Combined) isContextFrom_Type() {}

func (*contextFrom_Github) isContextFrom_Type() {}

func (*contextFrom_Cmd) isContextFrom_Type() {}

func (*contextFrom_Text) isContextFrom_Type() {}

func (*contextFrom_PrefetchId) isContextFrom_Type() {}

func (*contextFrom_UserInput) isContextFrom_Type() {}

func (*contextFrom_LocalFile) isContextFrom_Type() {}

func (*contextFrom_GitRepo) isContextFrom_Type() {}

func (*contextFrom_JiraIssues) isContextFrom_Type() {}

func (*contextFrom_LinearIssues) isContextFrom_Type() {}

func (*contextFrom_GitHistory) isContextFrom_Type() {}

// CombinedContextSource merges outputs from several individual sources.
type CombinedContextSource struct {
	state            protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*CombinedContextSource_Item `protobuf:"bytes,1,rep,name=items,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CombinedContextSource) Reset() {
	*x = CombinedContextSource{}
	mi := &file_osdd_recipes_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedContextSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedContextSource) ProtoMessage() {}

func (x *CombinedContextSource) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_recipes_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CombinedContextSource) GetItems() []*CombinedContextSource_Item {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *CombinedContextSource) SetItems(v []*CombinedContextSource_Item) {
	x.xxx_hidden_Items = &v
}

type CombinedContextSource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Items that will be concatenated in declaration order.
	Items []*CombinedContextSource_Item
}

func (b0 CombinedContextSource_builder) Build() *CombinedContextSource {
	m0 := &CombinedContextSource{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

// UserInputContextSource collects context provided interactively.
type UserInputContextSource struct {
	state              protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*osdd.UserInputParameter `protobuf:"bytes,1,rep,name=entries,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserInputContextSource) Reset() {
	*x = UserInputContextSource{}
	mi := &file_osdd_recipes_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInputContextSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInputContextSource) ProtoMessage() {}

func (x *UserInputContextSource) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_recipes_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserInputContextSource) GetEntries() []*osdd.UserInputParameter {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *UserInputContextSource) SetEntries(v []*osdd.UserInputParameter) {
	x.xxx_hidden_Entries = &v
}

type UserInputContextSource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Parameters that define the prompts shown to the user.
	Entries []*osdd.UserInputParameter
}

func (b0 UserInputContextSource_builder) Build() *UserInputContextSource {
	m0 := &UserInputContextSource{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type JiraIssuesSource struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SiteId          string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3"`
	xxx_hidden_Projects        []string               `protobuf:"bytes,2,rep,name=projects,proto3"`
	xxx_hidden_Filter          *IssuesFilter          `protobuf:"bytes,3,opt,name=filter,proto3,oneof"`
	xxx_hidden_AuthTokenEnvVar *string                `protobuf:"bytes,4,opt,name=auth_token_env_var,json=authTokenEnvVar,proto3,oneof"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *JiraIssuesSource) Reset() {
	*x = JiraIssuesSource{}
	mi := &file_osdd_recipes_context_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JiraIssuesSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JiraIssuesSource) ProtoMessage() {}

func (x *JiraIssuesSource) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_recipes_context_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JiraIssuesSource) GetSiteId() string {
	if x != nil {
		return x.xxx_hidden_SiteId
	}
	return ""
}

func (x *JiraIssuesSource) GetProjects() []string {
	if x != nil {
		return x.xxx_hidden_Projects
	}
	return nil
}

func (x *JiraIssuesSource) GetFilter() *IssuesFilter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *JiraIssuesSource) GetAuthTokenEnvVar() string {
	if x != nil {
		if x.xxx_hidden_AuthTokenEnvVar != nil {
			return *x.xxx_hidden_AuthTokenEnvVar
		}
		return ""
	}
	return ""
}

func (x *JiraIssuesSource) SetSiteId(v string) {
	x.xxx_hidden_SiteId = v
}

func (x *JiraIssuesSource) SetProjects(v []string) {
	x.xxx_hidden_Projects = v
}

func (x *JiraIssuesSource) SetFilter(v *IssuesFilter) {
	x.xxx_hidden_Filter = v
}

func (x *JiraIssuesSource) SetAuthTokenEnvVar(v string) {
	x.xxx_hidden_AuthTokenEnvVar = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *JiraIssuesSource) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *JiraIssuesSource) HasAuthTokenEnvVar() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *JiraIssuesSource) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

func (x *JiraIssuesSource) ClearAuthTokenEnvVar() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_AuthTokenEnvVar = nil
}

type JiraIssuesSource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Jira Cloud site ID (UUID). Used to construct the API gateway URL:
	// https://api.atlassian.com/ex/jira/{site_id}
	SiteId   string
	Projects []string
	Filter   *IssuesFilter
	// Name of the env var containing auth token. May be empty, then no token is used.
	AuthTokenEnvVar *string
}

func (b0 JiraIssuesSource_builder) Build() *JiraIssuesSource {
	m0 := &JiraIssuesSource{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SiteId = b.SiteId
	x.xxx_hidden_Projects = b.Projects
	x.xxx_hidden_Filter = b.Filter
	if b.AuthTokenEnvVar != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_AuthTokenEnvVar = b.AuthTokenEnvVar
	}
	return m0
}

type LinearIssuesSource struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Workspace       string                 `protobuf:"bytes,1,opt,name=workspace,proto3"`
	xxx_hidden_Teams           []string               `protobuf:"bytes,2,rep,name=teams,proto3"`
	xxx_hidden_Filter          *IssuesFilter          `protobuf:"bytes,3,opt,name=filter,proto3,oneof"`
	xxx_hidden_AuthTokenEnvVar *string                `protobuf:"bytes,4,opt,name=auth_token_env_var,json=authTokenEnvVar,proto3,oneof"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *LinearIssuesSource) Reset() {
	*x = LinearIssuesSource{}
	mi := &file_osdd_recipes_context_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinearIssuesSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearIssuesSource) ProtoMessage() {}

func (x *LinearIssuesSource) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_recipes_context_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LinearIssuesSource) GetWorkspace() string {
	if x != nil {
		return x.xxx_hidden_Workspace
	}
	return ""
}

func (x *LinearIssuesSource) GetTeams() []string {
	if x != nil {
		return x.xxx_hidden_Teams
	}
	return nil
}

func (x *LinearIssuesSource) GetFilter() *IssuesFilter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *LinearIssuesSource) GetAuthTokenEnvVar() string {
	if x != nil {
		if x.xxx_hidden_AuthTokenEnvVar != nil {
			return *x.xxx_hidden_AuthTokenEnvVar
		}
		return ""
	}
	return ""
}

func (x *LinearIssuesSource) SetWorkspace(v string) {
	x.xxx_hidden_Workspace = v
}

func (x *LinearIssuesSource) SetTeams(v []string) {
	x.xxx_hidden_Teams = v
}

func (x *LinearIssuesSource) SetFilter(v *IssuesFilter) {
	x.xxx_hidden_Filter = v
}

func (x *LinearIssuesSource) SetAuthTokenEnvVar(v string) {
	x.xxx_hidden_AuthTokenEnvVar = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *LinearIssuesSource) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *LinearIssuesSource) HasAuthTokenEnvVar() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *LinearIssuesSource) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

func (x *LinearIssuesSource) ClearAuthTokenEnvVar() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_AuthTokenEnvVar = nil
}

type LinearIssuesSource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Workspace string
	Teams     []string
	Filter    *IssuesFilter
	// Name of the env var containing auth token for the organization. May be empty, then no token is used.
	AuthTokenEnvVar *string
}

func (b0 LinearIssuesSource_builder) Build() *LinearIssuesSource {
	m0 := &LinearIssuesSource{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Workspace = b.Workspace
	x.xxx_hidden_Teams = b.Teams
	x.xxx_hidden_Filter = b.Filter
	if b.AuthTokenEnvVar != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_AuthTokenEnvVar = b.AuthTokenEnvVar
	}
	return m0
}

type IssuesFilter struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CreatedAtFilter *osdd.DatesFilter      `protobuf:"bytes,1,opt,name=created_at_filter,json=createdAtFilter,proto3,oneof"`
	xxx_hidden_UpdatedAtFilter *osdd.DatesFilter      `protobuf:"bytes,2,opt,name=updated_at_filter,json=updatedAtFilter,proto3,oneof"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *IssuesFilter) Reset() {
	*x = IssuesFilter{}
	mi := &file_osdd_recipes_context_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuesFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuesFilter) ProtoMessage() {}

func (x *IssuesFilter) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_recipes_context_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IssuesFilter) GetCreatedAtFilter() *osdd.DatesFilter {
	if x != nil {
		return x.xxx_hidden_CreatedAtFilter
	}
	return nil
}

func (x *IssuesFilter) GetUpdatedAtFilter() *osdd.DatesFilter {
	if x != nil {
		return x.xxx_hidden_UpdatedAtFilter
	}
	return nil
}

func (x *IssuesFilter) SetCreatedAtFilter(v *osdd.DatesFilter) {
	x.xxx_hidden_CreatedAtFilter = v
}

func (x *IssuesFilter) SetUpdatedAtFilter(v *osdd.DatesFilter) {
	x.xxx_hidden_UpdatedAtFilter = v
}

func (x *IssuesFilter) HasCreatedAtFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAtFilter != nil
}

func (x *IssuesFilter) HasUpdatedAtFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAtFilter != nil
}

func (x *IssuesFilter) ClearCreatedAtFilter() {
	x.xxx_hidden_CreatedAtFilter = nil
}

func (x *IssuesFilter) ClearUpdatedAtFilter() {
	x.xxx_hidden_UpdatedAtFilter = nil
}

type IssuesFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CreatedAtFilter *osdd.DatesFilter
	UpdatedAtFilter *osdd.DatesFilter
}

func (b0 IssuesFilter_builder) Build() *IssuesFilter {
	m0 := &IssuesFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CreatedAtFilter = b.CreatedAtFilter
	x.xxx_hidden_UpdatedAtFilter = b.UpdatedAtFilter
	return m0
}

type GitHistorySource struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Repo          *osdd.GitRepository    `protobuf:"bytes,1,opt,name=repo,proto3"`
	xxx_hidden_DateFilter    *osdd.DatesFilter      `protobuf:"bytes,2,opt,name=date_filter,json=dateFilter,proto3,oneof"`
	xxx_hidden_MaxFileTokens int32                  `protobuf:"varint,3,opt,name=max_file_tokens,json=maxFileTokens,proto3,oneof"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GitHistorySource) Reset() {
	*x = GitHistorySource{}
	mi := &file_osdd_recipes_context_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHistorySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHistorySource) ProtoMessage() {}

func (x *GitHistorySource) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_recipes_context_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GitHistorySource) GetRepo() *osdd.GitRepository {
	if x != nil {
		return x.xxx_hidden_Repo
	}
	return nil
}

func (x *GitHistorySource) GetDateFilter() *osdd.DatesFilter {
	if x != nil {
		return x.xxx_hidden_DateFilter
	}
	return nil
}

func (x *GitHistorySource) GetMaxFileTokens() int32 {
	if x != nil {
		return x.xxx_hidden_MaxFileTokens
	}
	return 0
}

func (x *GitHistorySource) SetRepo(v *osdd.GitRepository) {
	x.xxx_hidden_Repo = v
}

func (x *GitHistorySource) SetDateFilter(v *osdd.DatesFilter) {
	x.xxx_hidden_DateFilter = v
}

func (x *GitHistorySource) SetMaxFileTokens(v int32) {
	x.xxx_hidden_MaxFileTokens = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *GitHistorySource) HasRepo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Repo != nil
}

func (x *GitHistorySource) HasDateFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateFilter != nil
}

func (x *GitHistorySource) HasMaxFileTokens() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GitHistorySource) ClearRepo() {
	x.xxx_hidden_Repo = nil
}

func (x *GitHistorySource) ClearDateFilter() {
	x.xxx_hidden_DateFilter = nil
}

func (x *GitHistorySource) ClearMaxFileTokens() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MaxFileTokens = 0
}

type GitHistorySource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Repository to fetch history from (cloned temporarily).
	Repo *osdd.GitRepository
	// Date range for commits and PRs. Both from and to are inclusive.
	DateFilter *osdd.DatesFilter
	// Maximum estimated tokens per output file. Content is split at
	// commit/PR boundaries when this limit is exceeded. Default: 50000.
	MaxFileTokens *int32
}

func (b0 GitHistorySource_builder) Build() *GitHistorySource {
	m0 := &GitHistorySource{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Repo = b.Repo
	x.xxx_hidden_DateFilter = b.DateFilter
	if b.MaxFileTokens != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_MaxFileTokens = *b.MaxFileTokens
	}
	return m0
}

// Item represents a single source contributing to the combined content.
type CombinedContextSource_Item struct {
	state           protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_Type isCombinedContextSource_Item_Type `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CombinedContextSource_Item) Reset() {
	*x = CombinedContextSource_Item{}
	mi := &file_osdd_recipes_context_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedContextSource_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedContextSource_Item) ProtoMessage() {}

func (x *CombinedContextSource_Item) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_recipes_context_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CombinedContextSource_Item) GetGithub() *osdd.GitReference {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_Github); ok {
			return x.Github
		}
	}
	return nil
}

func (x *CombinedContextSource_Item) GetCmd() *osdd.Exec {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_Cmd); ok {
			return x.Cmd
		}
	}
	return nil
}

func (x *CombinedContextSource_Item) GetText() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *CombinedContextSource_Item) GetPrefetchId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_PrefetchId); ok {
			return x.PrefetchId
		}
	}
	return ""
}

func (x *CombinedContextSource_Item) GetUserInput() *UserInputContextSource {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_UserInput); ok {
			return x.UserInput
		}
	}
	return nil
}

func (x *CombinedContextSource_Item) GetLocalFile() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_LocalFile); ok {
			return x.LocalFile
		}
	}
	return ""
}

func (x *CombinedContextSource_Item) SetGithub(v *osdd.GitReference) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &combinedContextSource_Item_Github{v}
}

func (x *CombinedContextSource_Item) SetCmd(v *osdd.Exec) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &combinedContextSource_Item_Cmd{v}
}

func (x *CombinedContextSource_Item) SetText(v string) {
	x.xxx_hidden_Type = &combinedContextSource_Item_Text{v}
}

func (x *CombinedContextSource_Item) SetPrefetchId(v string) {
	x.xxx_hidden_Type = &combinedContextSource_Item_PrefetchId{v}
}

func (x *CombinedContextSource_Item) SetUserInput(v *UserInputContextSource) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &combinedContextSource_Item_UserInput{v}
}

func (x *CombinedContextSource_Item) SetLocalFile(v string) {
	x.xxx_hidden_Type = &combinedContextSource_Item_LocalFile{v}
}

func (x *CombinedContextSource_Item) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *CombinedContextSource_Item) HasGithub() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_Github)
	return ok
}

func (x *CombinedContextSource_Item) HasCmd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_Cmd)
	return ok
}

func (x *CombinedContextSource_Item) HasText() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_Text)
	return ok
}

func (x *CombinedContextSource_Item) HasPrefetchId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_PrefetchId)
	return ok
}

func (x *CombinedContextSource_Item) HasUserInput() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_UserInput)
	return ok
}

func (x *CombinedContextSource_Item) HasLocalFile() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_LocalFile)
	return ok
}

func (x *CombinedContextSource_Item) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *CombinedContextSource_Item) ClearGithub() {
	if _, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_Github); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *CombinedContextSource_Item) ClearCmd() {
	if _, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_Cmd); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *CombinedContextSource_Item) ClearText() {
	if _, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_Text); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *CombinedContextSource_Item) ClearPrefetchId() {
	if _, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_PrefetchId); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *CombinedContextSource_Item) ClearUserInput() {
	if _, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_UserInput); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *CombinedContextSource_Item) ClearLocalFile() {
	if _, ok := x.xxx_hidden_Type.(*combinedContextSource_Item_LocalFile); ok {
		x.xxx_hidden_Type = nil
	}
}

const CombinedContextSource_Item_Type_not_set_case case_CombinedContextSource_Item_Type = 0
const CombinedContextSource_Item_Github_case case_CombinedContextSource_Item_Type = 100
const CombinedContextSource_Item_Cmd_case case_CombinedContextSource_Item_Type = 101
const CombinedContextSource_Item_Text_case case_CombinedContextSource_Item_Type = 102
const CombinedContextSource_Item_PrefetchId_case case_CombinedContextSource_Item_Type = 103
const CombinedContextSource_Item_UserInput_case case_CombinedContextSource_Item_Type = 104
const CombinedContextSource_Item_LocalFile_case case_CombinedContextSource_Item_Type = 105

func (x *CombinedContextSource_Item) WhichType() case_CombinedContextSource_Item_Type {
	if x == nil {
		return CombinedContextSource_Item_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *combinedContextSource_Item_Github:
		return CombinedContextSource_Item_Github_case
	case *combinedContextSource_Item_Cmd:
		return CombinedContextSource_Item_Cmd_case
	case *combinedContextSource_Item_Text:
		return CombinedContextSource_Item_Text_case
	case *combinedContextSource_Item_PrefetchId:
		return CombinedContextSource_Item_PrefetchId_case
	case *combinedContextSource_Item_UserInput:
		return CombinedContextSource_Item_UserInput_case
	case *combinedContextSource_Item_LocalFile:
		return CombinedContextSource_Item_LocalFile_case
	default:
		return CombinedContextSource_Item_Type_not_set_case
	}
}

type CombinedContextSource_Item_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Chosen source type used to fetch data.

	// Fields of oneof xxx_hidden_Type:
	// Fetch content from a Git repository.
	Github *osdd.GitReference
	// Execute a command and capture its output.
	Cmd *osdd.Exec
	// Inline text content embedded in the recipe.
	Text *string
	// Reference to a blob returned by PrefetchResult.
	PrefetchId *string
	// Prompt user for the content at runtime.
	UserInput *UserInputContextSource
	// Local file should be mostly used for tests. If the provided path is relative, then it will be relative to the
	// current working directory.
	LocalFile *string
	// -- end of xxx_hidden_Type
}

func (b0 CombinedContextSource_Item_builder) Build() *CombinedContextSource_Item {
	m0 := &CombinedContextSource_Item{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Github != nil {
		x.xxx_hidden_Type = &combinedContextSource_Item_Github{b.Github}
	}
	if b.Cmd != nil {
		x.xxx_hidden_Type = &combinedContextSource_Item_Cmd{b.Cmd}
	}
	if b.Text != nil {
		x.xxx_hidden_Type = &combinedContextSource_Item_Text{*b.Text}
	}
	if b.PrefetchId != nil {
		x.xxx_hidden_Type = &combinedContextSource_Item_PrefetchId{*b.PrefetchId}
	}
	if b.UserInput != nil {
		x.xxx_hidden_Type = &combinedContextSource_Item_UserInput{b.UserInput}
	}
	if b.LocalFile != nil {
		x.xxx_hidden_Type = &combinedContextSource_Item_LocalFile{*b.LocalFile}
	}
	return m0
}

type case_CombinedContextSource_Item_Type protoreflect.FieldNumber

func (x case_CombinedContextSource_Item_Type) String() string {
	md := file_osdd_recipes_context_proto_msgTypes[9].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isCombinedContextSource_Item_Type interface {
	isCombinedContextSource_Item_Type()
}

type combinedContextSource_Item_Github struct {
	// Fetch content from a Git repository.
	Github *osdd.GitReference `protobuf:"bytes,100,opt,name=github,proto3,oneof"`
}

type combinedContextSource_Item_Cmd struct {
	// Execute a command and capture its output.
	Cmd *osdd.Exec `protobuf:"bytes,101,opt,name=cmd,proto3,oneof"`
}

type combinedContextSource_Item_Text struct {
	// Inline text content embedded in the recipe.
	Text string `protobuf:"bytes,102,opt,name=text,proto3,oneof"`
}

type combinedContextSource_Item_PrefetchId struct {
	// Reference to a blob returned by PrefetchResult.
	PrefetchId string `protobuf:"bytes,103,opt,name=prefetch_id,json=prefetchId,proto3,oneof"`
}

type combinedContextSource_Item_UserInput struct {
	// Prompt user for the content at runtime.
	UserInput *UserInputContextSource `protobuf:"bytes,104,opt,name=user_input,json=userInput,proto3,oneof"`
}

type combinedContextSource_Item_LocalFile struct {
	// Local file should be mostly used for tests. If the provided path is relative, then it will be relative to the
	// current working directory.
	LocalFile string `protobuf:"bytes,105,opt,name=local_file,json=localFile,proto3,oneof"`
}

func (*combinedContextSource_Item_Github) isCombinedContextSource_Item_Type() {}

func (*combinedContextSource_Item_Cmd) isCombinedContextSource_Item_Type() {}

func (*combinedContextSource_Item_Text) isCombinedContextSource_Item_Type() {}

func (*combinedContextSource_Item_PrefetchId) isCombinedContextSource_Item_Type() {}

func (*combinedContextSource_Item_UserInput) isCombinedContextSource_Item_Type() {}

func (*combinedContextSource_Item_LocalFile) isCombinedContextSource_Item_Type() {}

var File_osdd_recipes_context_proto protoreflect.FileDescriptor

const file_osdd_recipes_context_proto_rawDesc = "" +
	"\n" +
	"\x1aosdd/recipes/context.proto\x12\x14osdd.recipes.context\x1a\x11osdd/common.proto\"G\n" +
	"\aContext\x12<\n" +
	"\aentries\x18\x01 \x03(\v2\".osdd.recipes.context.ContextEntryR\aentries\"\x9b\x01\n" +
	"\fContextEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x125\n" +
	"\x04from\x18\x02 \x01(\v2!.osdd.recipes.context.ContextFromR\x04from\x125\n" +
	"\x06filter\x18\x03 \x01(\v2\x18.osdd.common.EntryFilterH\x00R\x06filter\x88\x01\x01B\t\n" +
	"\a_filter\"\x85\x05\n" +
	"\vContextFrom\x12I\n" +
	"\bcombined\x18d \x01(\v2+.osdd.recipes.context.CombinedContextSourceH\x00R\bcombined\x123\n" +
	"\x06github\x18e \x01(\v2\x19.osdd.common.GitReferenceH\x00R\x06github\x12%\n" +
	"\x03cmd\x18f \x01(\v2\x11.osdd.common.ExecH\x00R\x03cmd\x12\x14\n" +
	"\x04text\x18g \x01(\tH\x00R\x04text\x12!\n" +
	"\vprefetch_id\x18h \x01(\tH\x00R\n" +
	"prefetchId\x12M\n" +
	"\n" +
	"user_input\x18i \x01(\v2,.osdd.recipes.context.UserInputContextSourceH\x00R\tuserInput\x12\x1f\n" +
	"\n" +
	"local_file\x18j \x01(\tH\x00R\tlocalFile\x127\n" +
	"\bgit_repo\x18k \x01(\v2\x1a.osdd.common.GitRepositoryH\x00R\agitRepo\x12I\n" +
	"\vjira_issues\x18l \x01(\v2&.osdd.recipes.context.JiraIssuesSourceH\x00R\n" +
	"jiraIssues\x12O\n" +
	"\rlinear_issues\x18m \x01(\v2(.osdd.recipes.context.LinearIssuesSourceH\x00R\flinearIssues\x12I\n" +
	"\vgit_history\x18n \x01(\v2&.osdd.recipes.context.GitHistorySourceH\x00R\n" +
	"gitHistoryB\x06\n" +
	"\x04type\"\xf5\x02\n" +
	"\x15CombinedContextSource\x12F\n" +
	"\x05items\x18\x01 \x03(\v20.osdd.recipes.context.CombinedContextSource.ItemR\x05items\x1a\x93\x02\n" +
	"\x04Item\x123\n" +
	"\x06github\x18d \x01(\v2\x19.osdd.common.GitReferenceH\x00R\x06github\x12%\n" +
	"\x03cmd\x18e \x01(\v2\x11.osdd.common.ExecH\x00R\x03cmd\x12\x14\n" +
	"\x04text\x18f \x01(\tH\x00R\x04text\x12!\n" +
	"\vprefetch_id\x18g \x01(\tH\x00R\n" +
	"prefetchId\x12M\n" +
	"\n" +
	"user_input\x18h \x01(\v2,.osdd.recipes.context.UserInputContextSourceH\x00R\tuserInput\x12\x1f\n" +
	"\n" +
	"local_file\x18i \x01(\tH\x00R\tlocalFileB\x06\n" +
	"\x04type\"S\n" +
	"\x16UserInputContextSource\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.osdd.common.UserInputParameterR\aentries\"\xdc\x01\n" +
	"\x10JiraIssuesSource\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12\x1a\n" +
	"\bprojects\x18\x02 \x03(\tR\bprojects\x12?\n" +
	"\x06filter\x18\x03 \x01(\v2\".osdd.recipes.context.IssuesFilterH\x00R\x06filter\x88\x01\x01\x120\n" +
	"\x12auth_token_env_var\x18\x04 \x01(\tH\x01R\x0fauthTokenEnvVar\x88\x01\x01B\t\n" +
	"\a_filterB\x15\n" +
	"\x13_auth_token_env_var\"\xdd\x01\n" +
	"\x12LinearIssuesSource\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x14\n" +
	"\x05teams\x18\x02 \x03(\tR\x05teams\x12?\n" +
	"\x06filter\x18\x03 \x01(\v2\".osdd.recipes.context.IssuesFilterH\x00R\x06filter\x88\x01\x01\x120\n" +
	"\x12auth_token_env_var\x18\x04 \x01(\tH\x01R\x0fauthTokenEnvVar\x88\x01\x01B\t\n" +
	"\a_filterB\x15\n" +
	"\x13_auth_token_env_var\"\xd0\x01\n" +
	"\fIssuesFilter\x12I\n" +
	"\x11created_at_filter\x18\x01 \x01(\v2\x18.osdd.common.DatesFilterH\x00R\x0fcreatedAtFilter\x88\x01\x01\x12I\n" +
	"\x11updated_at_filter\x18\x02 \x01(\v2\x18.osdd.common.DatesFilterH\x01R\x0fupdatedAtFilter\x88\x01\x01B\x14\n" +
	"\x12_created_at_filterB\x14\n" +
	"\x12_updated_at_filter\"\xd3\x01\n" +
	"\x10GitHistorySource\x12.\n" +
	"\x04repo\x18\x01 \x01(\v2\x1a.osdd.common.GitRepositoryR\x04repo\x12>\n" +
	"\vdate_filter\x18\x02 \x01(\v2\x18.osdd.common.DatesFilterH\x00R\n" +
	"dateFilter\x88\x01\x01\x12+\n" +
	"\x0fmax_file_tokens\x18\x03 \x01(\x05H\x01R\rmaxFileTokens\x88\x01\x01B\x0e\n" +
	"\f_date_filterB\x12\n" +
	"\x10_max_file_tokensB5Z3github.com/opensdd/osdd-api/clients/go/osdd/recipesb\x06proto3"

var file_osdd_recipes_context_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_osdd_recipes_context_proto_goTypes = []any{
	(*Context)(nil),                    // 0: osdd.recipes.context.Context
	(*ContextEntry)(nil),               // 1: osdd.recipes.context.ContextEntry
	(*ContextFrom)(nil),                // 2: osdd.recipes.context.ContextFrom
	(*CombinedContextSource)(nil),      // 3: osdd.recipes.context.CombinedContextSource
	(*UserInputContextSource)(nil),     // 4: osdd.recipes.context.UserInputContextSource
	(*JiraIssuesSource)(nil),           // 5: osdd.recipes.context.JiraIssuesSource
	(*LinearIssuesSource)(nil),         // 6: osdd.recipes.context.LinearIssuesSource
	(*IssuesFilter)(nil),               // 7: osdd.recipes.context.IssuesFilter
	(*GitHistorySource)(nil),           // 8: osdd.recipes.context.GitHistorySource
	(*CombinedContextSource_Item)(nil), // 9: osdd.recipes.context.CombinedContextSource.Item
	(*osdd.EntryFilter)(nil),           // 10: osdd.common.EntryFilter
	(*osdd.GitReference)(nil),          // 11: osdd.common.GitReference
	(*osdd.Exec)(nil),                  // 12: osdd.common.Exec
	(*osdd.GitRepository)(nil),         // 13: osdd.common.GitRepository
	(*osdd.UserInputParameter)(nil),    // 14: osdd.common.UserInputParameter
	(*osdd.DatesFilter)(nil),           // 15: osdd.common.DatesFilter
}
var file_osdd_recipes_context_proto_depIdxs = []int32{
	1,  // 0: osdd.recipes.context.Context.entries:type_name -> osdd.recipes.context.ContextEntry
	2,  // 1: osdd.recipes.context.ContextEntry.from:type_name -> osdd.recipes.context.ContextFrom
	10, // 2: osdd.recipes.context.ContextEntry.filter:type_name -> osdd.common.EntryFilter
	3,  // 3: osdd.recipes.context.ContextFrom.combined:type_name -> osdd.recipes.context.CombinedContextSource
	11, // 4: osdd.recipes.context.ContextFrom.github:type_name -> osdd.common.GitReference
	12, // 5: osdd.recipes.context.ContextFrom.cmd:type_name -> osdd.common.Exec
	4,  // 6: osdd.recipes.context.ContextFrom.user_input:type_name -> osdd.recipes.context.UserInputContextSource
	13, // 7: osdd.recipes.context.ContextFrom.git_repo:type_name -> osdd.common.GitRepository
	5,  // 8: osdd.recipes.context.ContextFrom.jira_issues:type_name -> osdd.recipes.context.JiraIssuesSource
	6,  // 9: osdd.recipes.context.ContextFrom.linear_issues:type_name -> osdd.recipes.context.LinearIssuesSource
	8,  // 10: osdd.recipes.context.ContextFrom.git_history:type_name -> osdd.recipes.context.GitHistorySource
	9,  // 11: osdd.recipes.context.CombinedContextSource.items:type_name -> osdd.recipes.context.CombinedContextSource.Item
	14, // 12: osdd.recipes.context.UserInputContextSource.entries:type_name -> osdd.common.UserInputParameter
	7,  // 13: osdd.recipes.context.JiraIssuesSource.filter:type_name -> osdd.recipes.context.IssuesFilter
	7,  // 14: osdd.recipes.context.LinearIssuesSource.filter:type_name -> osdd.recipes.context.IssuesFilter
	15, // 15: osdd.recipes.context.IssuesFilter.created_at_filter:type_name -> osdd.common.DatesFilter
	15, // 16: osdd.recipes.context.IssuesFilter.updated_at_filter:type_name -> osdd.common.DatesFilter
	13, // 17: osdd.recipes.context.GitHistorySource.repo:type_name -> osdd.common.GitRepository
	15, // 18: osdd.recipes.context.GitHistorySource.date_filter:type_name -> osdd.common.DatesFilter
	11, // 19: osdd.recipes.context.CombinedContextSource.Item.github:type_name -> osdd.common.GitReference
	12, // 20: osdd.recipes.context.CombinedContextSource.Item.cmd:type_name -> osdd.common.Exec
	4,  // 21: osdd.recipes.context.CombinedContextSource.Item.user_input:type_name -> osdd.recipes.context.UserInputContextSource
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_osdd_recipes_context_proto_init() }
func file_osdd_recipes_context_proto_init() {
	if File_osdd_recipes_context_proto != nil {
		return
	}
	file_osdd_recipes_context_proto_msgTypes[1].OneofWrappers = []any{}
	file_osdd_recipes_context_proto_msgTypes[2].OneofWrappers = []any{
		(*contextFrom_Combined)(nil),
		(*contextFrom_Github)(nil),
		(*contextFrom_Cmd)(nil),
		(*contextFrom_Text)(nil),
		(*contextFrom_PrefetchId)(nil),
		(*contextFrom_UserInput)(nil),
		(*contextFrom_LocalFile)(nil),
		(*contextFrom_GitRepo)(nil),
		(*contextFrom_JiraIssues)(nil),
		(*contextFrom_LinearIssues)(nil),
		(*contextFrom_GitHistory)(nil),
	}
	file_osdd_recipes_context_proto_msgTypes[5].OneofWrappers = []any{}
	file_osdd_recipes_context_proto_msgTypes[6].OneofWrappers = []any{}
	file_osdd_recipes_context_proto_msgTypes[7].OneofWrappers = []any{}
	file_osdd_recipes_context_proto_msgTypes[8].OneofWrappers = []any{}
	file_osdd_recipes_context_proto_msgTypes[9].OneofWrappers = []any{
		(*combinedContextSource_Item_Github)(nil),
		(*combinedContextSource_Item_Cmd)(nil),
		(*combinedContextSource_Item_Text)(nil),
		(*combinedContextSource_Item_PrefetchId)(nil),
		(*combinedContextSource_Item_UserInput)(nil),
		(*combinedContextSource_Item_LocalFile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osdd_recipes_context_proto_rawDesc), len(file_osdd_recipes_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osdd_recipes_context_proto_goTypes,
		DependencyIndexes: file_osdd_recipes_context_proto_depIdxs,
		MessageInfos:      file_osdd_recipes_context_proto_msgTypes,
	}.Build()
	File_osdd_recipes_context_proto = out.File
	file_osdd_recipes_context_proto_goTypes = nil
	file_osdd_recipes_context_proto_depIdxs = nil
}
