# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osdd/recipes/context.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'osdd/recipes/context.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osdd import common_pb2 as osdd_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aosdd/recipes/context.proto\x12\x14osdd.recipes.context\x1a\x11osdd/common.proto\">\n\x07\x43ontext\x12\x33\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\".osdd.recipes.context.ContextEntry\"M\n\x0c\x43ontextEntry\x12\x0c\n\x04path\x18\x01 \x01(\t\x12/\n\x04\x66rom\x18\x02 \x01(\x0b\x32!.osdd.recipes.context.ContextFrom\"\xb9\x01\n\x0b\x43ontextFrom\x12?\n\x08\x63ombined\x18\x64 \x01(\x0b\x32+.osdd.recipes.context.CombinedContextSourceH\x00\x12+\n\x06github\x18\x65 \x01(\x0b\x32\x19.osdd.common.GitReferenceH\x00\x12\r\n\x03\x63md\x18\x66 \x01(\tH\x00\x12\x0e\n\x04text\x18g \x01(\tH\x00\x12\x15\n\x0bprefetch_id\x18h \x01(\tH\x00\x42\x06\n\x04type\"\xcb\x01\n\x15\x43ombinedContextSource\x12?\n\x05items\x18\x01 \x03(\x0b\x32\x30.osdd.recipes.context.CombinedContextSource.Item\x1aq\n\x04Item\x12+\n\x06github\x18\x64 \x01(\x0b\x32\x19.osdd.common.GitReferenceH\x00\x12\r\n\x03\x63md\x18\x65 \x01(\tH\x00\x12\x0e\n\x04text\x18\x66 \x01(\tH\x00\x12\x15\n\x0bprefetch_id\x18g \x01(\tH\x00\x42\x06\n\x04typeB5Z3github.com/opensdd/osdd-api/clients/go/osdd/recipesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osdd.recipes.context_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/opensdd/osdd-api/clients/go/osdd/recipes'
  _globals['_CONTEXT']._serialized_start=71
  _globals['_CONTEXT']._serialized_end=133
  _globals['_CONTEXTENTRY']._serialized_start=135
  _globals['_CONTEXTENTRY']._serialized_end=212
  _globals['_CONTEXTFROM']._serialized_start=215
  _globals['_CONTEXTFROM']._serialized_end=400
  _globals['_COMBINEDCONTEXTSOURCE']._serialized_start=403
  _globals['_COMBINEDCONTEXTSOURCE']._serialized_end=606
  _globals['_COMBINEDCONTEXTSOURCE_ITEM']._serialized_start=493
  _globals['_COMBINEDCONTEXTSOURCE_ITEM']._serialized_end=606
# @@protoc_insertion_point(module_scope)
