# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osdd/recipes/permissions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'osdd/recipes/permissions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eosdd/recipes/permissions.proto\x12\x18osdd.recipes.permissions\"N\n\x13OperationPermission\x12\x0e\n\x04\x62\x61sh\x18\x64 \x01(\tH\x00\x12\x0e\n\x04read\x18\x65 \x01(\tH\x00\x12\x0f\n\x05write\x18\x66 \x01(\tH\x00\x42\x06\n\x04type\"\x88\x01\n\x0bPermissions\x12<\n\x05\x61llow\x18\x01 \x03(\x0b\x32-.osdd.recipes.permissions.OperationPermission\x12;\n\x04\x64\x65ny\x18\x02 \x03(\x0b\x32-.osdd.recipes.permissions.OperationPermissionB5Z3github.com/opensdd/osdd-api/clients/go/osdd/recipesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osdd.recipes.permissions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/opensdd/osdd-api/clients/go/osdd/recipes'
  _globals['_OPERATIONPERMISSION']._serialized_start=60
  _globals['_OPERATIONPERMISSION']._serialized_end=138
  _globals['_PERMISSIONS']._serialized_start=141
  _globals['_PERMISSIONS']._serialized_end=277
# @@protoc_insertion_point(module_scope)
