# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osdd/recipes/recipe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'osdd/recipes/recipe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osdd.recipes import context_pb2 as osdd_dot_recipes_dot_context__pb2
from osdd.recipes import ide_pb2 as osdd_dot_recipes_dot_ide__pb2
from osdd import content_pb2 as osdd_dot_content__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19osdd/recipes/recipe.proto\x12\x13osdd.recipes.recipe\x1a\x1aosdd/recipes/context.proto\x1a\x16osdd/recipes/ide.proto\x1a\x12osdd/content.proto\"\xb6\x01\n\x06Recipe\x12-\n\x08prefetch\x18\x01 \x01(\x0b\x32\x16.osdd.content.PrefetchH\x00\x88\x01\x01\x12\x33\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x1d.osdd.recipes.context.ContextH\x01\x88\x01\x01\x12\'\n\x03ide\x18\x03 \x01(\x0b\x32\x15.osdd.recipes.ide.IdeH\x02\x88\x01\x01\x42\x0b\n\t_prefetchB\n\n\x08_contextB\x06\n\x04_ide\"u\n\x10\x45xecutableRecipe\x12+\n\x06recipe\x18\x01 \x01(\x0b\x32\x1b.osdd.recipes.recipe.Recipe\x12\x34\n\x0b\x65ntry_point\x18\x02 \x01(\x0b\x32\x1f.osdd.recipes.recipe.EntryPoint\"\x1e\n\nEntryPoint\x12\x10\n\x08ide_type\x18\x01 \x01(\tB5Z3github.com/opensdd/osdd-api/clients/go/osdd/recipesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osdd.recipes.recipe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/opensdd/osdd-api/clients/go/osdd/recipes'
  _globals['_RECIPE']._serialized_start=123
  _globals['_RECIPE']._serialized_end=305
  _globals['_EXECUTABLERECIPE']._serialized_start=307
  _globals['_EXECUTABLERECIPE']._serialized_end=424
  _globals['_ENTRYPOINT']._serialized_start=426
  _globals['_ENTRYPOINT']._serialized_end=456
# @@protoc_insertion_point(module_scope)
