# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osdd/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'osdd/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11osdd/common.proto\x12\x0bosdd.common\"W\n\x0cGitReference\x12\x0c\n\x04path\x18\x01 \x01(\t\x12-\n\x07version\x18\x02 \x01(\x0b\x32\x17.osdd.common.GitVersionH\x00\x88\x01\x01\x42\n\n\x08_version\"5\n\nGitVersion\x12\r\n\x03tag\x18\x64 \x01(\tH\x00\x12\x10\n\x06\x63ommit\x18\x65 \x01(\tH\x00\x42\x06\n\x04typeB-Z+github.com/opensdd/osdd-api/clients/go/osddb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osdd.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/opensdd/osdd-api/clients/go/osdd'
  _globals['_GITREFERENCE']._serialized_start=34
  _globals['_GITREFERENCE']._serialized_end=121
  _globals['_GITVERSION']._serialized_start=123
  _globals['_GITVERSION']._serialized_end=176
# @@protoc_insertion_point(module_scope)
