// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: osdd/common.proto

package osdd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GitReference identifies a file or directory stored in a Git repository.
type GitReference struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path    string                 `protobuf:"bytes,1,opt,name=path,proto3"`
	xxx_hidden_Version *GitVersion            `protobuf:"bytes,2,opt,name=version,proto3,oneof"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GitReference) Reset() {
	*x = GitReference{}
	mi := &file_osdd_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitReference) ProtoMessage() {}

func (x *GitReference) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GitReference) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *GitReference) GetVersion() *GitVersion {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return nil
}

func (x *GitReference) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *GitReference) SetVersion(v *GitVersion) {
	x.xxx_hidden_Version = v
}

func (x *GitReference) HasVersion() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Version != nil
}

func (x *GitReference) ClearVersion() {
	x.xxx_hidden_Version = nil
}

type GitReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Relative path within the repository that should be fetched.
	Path string
	// Optional revision selector (tag or commit SHA) to pin the lookup.
	Version *GitVersion
}

func (b0 GitReference_builder) Build() *GitReference {
	m0 := &GitReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_Version = b.Version
	return m0
}

type GitRepository struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FullName        string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3"`
	xxx_hidden_Provider        string                 `protobuf:"bytes,2,opt,name=provider,proto3"`
	xxx_hidden_AuthTokenEnvVar *string                `protobuf:"bytes,3,opt,name=auth_token_env_var,json=authTokenEnvVar,proto3,oneof"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GitRepository) Reset() {
	*x = GitRepository{}
	mi := &file_osdd_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitRepository) ProtoMessage() {}

func (x *GitRepository) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GitRepository) GetFullName() string {
	if x != nil {
		return x.xxx_hidden_FullName
	}
	return ""
}

func (x *GitRepository) GetProvider() string {
	if x != nil {
		return x.xxx_hidden_Provider
	}
	return ""
}

func (x *GitRepository) GetAuthTokenEnvVar() string {
	if x != nil {
		if x.xxx_hidden_AuthTokenEnvVar != nil {
			return *x.xxx_hidden_AuthTokenEnvVar
		}
		return ""
	}
	return ""
}

func (x *GitRepository) SetFullName(v string) {
	x.xxx_hidden_FullName = v
}

func (x *GitRepository) SetProvider(v string) {
	x.xxx_hidden_Provider = v
}

func (x *GitRepository) SetAuthTokenEnvVar(v string) {
	x.xxx_hidden_AuthTokenEnvVar = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *GitRepository) HasAuthTokenEnvVar() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GitRepository) ClearAuthTokenEnvVar() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_AuthTokenEnvVar = nil
}

type GitRepository_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Full name of the repository in the format "owner/name".
	FullName string
	// Supported github, bitbucket.
	Provider string
	// Name of the env var containing auth token for the repository. May be empty, then no token is used.
	AuthTokenEnvVar *string
}

func (b0 GitRepository_builder) Build() *GitRepository {
	m0 := &GitRepository{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FullName = b.FullName
	x.xxx_hidden_Provider = b.Provider
	if b.AuthTokenEnvVar != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_AuthTokenEnvVar = b.AuthTokenEnvVar
	}
	return m0
}

// GitVersion specifies the exact revision to use for a Git reference.
type GitVersion struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type isGitVersion_Type      `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GitVersion) Reset() {
	*x = GitVersion{}
	mi := &file_osdd_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitVersion) ProtoMessage() {}

func (x *GitVersion) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GitVersion) GetTag() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*gitVersion_Tag); ok {
			return x.Tag
		}
	}
	return ""
}

func (x *GitVersion) GetCommit() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*gitVersion_Commit); ok {
			return x.Commit
		}
	}
	return ""
}

func (x *GitVersion) SetTag(v string) {
	x.xxx_hidden_Type = &gitVersion_Tag{v}
}

func (x *GitVersion) SetCommit(v string) {
	x.xxx_hidden_Type = &gitVersion_Commit{v}
}

func (x *GitVersion) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *GitVersion) HasTag() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*gitVersion_Tag)
	return ok
}

func (x *GitVersion) HasCommit() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*gitVersion_Commit)
	return ok
}

func (x *GitVersion) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *GitVersion) ClearTag() {
	if _, ok := x.xxx_hidden_Type.(*gitVersion_Tag); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *GitVersion) ClearCommit() {
	if _, ok := x.xxx_hidden_Type.(*gitVersion_Commit); ok {
		x.xxx_hidden_Type = nil
	}
}

const GitVersion_Type_not_set_case case_GitVersion_Type = 0
const GitVersion_Tag_case case_GitVersion_Type = 100
const GitVersion_Commit_case case_GitVersion_Type = 101

func (x *GitVersion) WhichType() case_GitVersion_Type {
	if x == nil {
		return GitVersion_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *gitVersion_Tag:
		return GitVersion_Tag_case
	case *gitVersion_Commit:
		return GitVersion_Commit_case
	default:
		return GitVersion_Type_not_set_case
	}
}

type GitVersion_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Type of revision identifier supplied by the recipe.

	// Fields of oneof xxx_hidden_Type:
	// Named Git tag such as v1.2.3.
	Tag *string
	// Commit SHA (full or abbreviated).
	Commit *string
	// -- end of xxx_hidden_Type
}

func (b0 GitVersion_builder) Build() *GitVersion {
	m0 := &GitVersion{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Tag != nil {
		x.xxx_hidden_Type = &gitVersion_Tag{*b.Tag}
	}
	if b.Commit != nil {
		x.xxx_hidden_Type = &gitVersion_Commit{*b.Commit}
	}
	return m0
}

type case_GitVersion_Type protoreflect.FieldNumber

func (x case_GitVersion_Type) String() string {
	md := file_osdd_common_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isGitVersion_Type interface {
	isGitVersion_Type()
}

type gitVersion_Tag struct {
	// Named Git tag such as v1.2.3.
	Tag string `protobuf:"bytes,100,opt,name=tag,proto3,oneof"`
}

type gitVersion_Commit struct {
	// Commit SHA (full or abbreviated).
	Commit string `protobuf:"bytes,101,opt,name=commit,proto3,oneof"`
}

func (*gitVersion_Tag) isGitVersion_Type() {}

func (*gitVersion_Commit) isGitVersion_Type() {}

// UserInputParameter declares a parameter collected from the end user.
type UserInputParameter struct {
	state                  protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Name        string                    `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Description string                    `protobuf:"bytes,2,opt,name=description,proto3"`
	xxx_hidden_Optional    bool                      `protobuf:"varint,3,opt,name=optional,proto3"`
	xxx_hidden_Type        isUserInputParameter_Type `protobuf_oneof:"type"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserInputParameter) Reset() {
	*x = UserInputParameter{}
	mi := &file_osdd_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInputParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInputParameter) ProtoMessage() {}

func (x *UserInputParameter) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserInputParameter) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *UserInputParameter) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *UserInputParameter) GetOptional() bool {
	if x != nil {
		return x.xxx_hidden_Optional
	}
	return false
}

func (x *UserInputParameter) GetText() *UserInputParameter_Text {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*userInputParameter_Text_); ok {
			return x.Text
		}
	}
	return nil
}

func (x *UserInputParameter) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *UserInputParameter) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *UserInputParameter) SetOptional(v bool) {
	x.xxx_hidden_Optional = v
}

func (x *UserInputParameter) SetText(v *UserInputParameter_Text) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &userInputParameter_Text_{v}
}

func (x *UserInputParameter) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *UserInputParameter) HasText() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*userInputParameter_Text_)
	return ok
}

func (x *UserInputParameter) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *UserInputParameter) ClearText() {
	if _, ok := x.xxx_hidden_Type.(*userInputParameter_Text_); ok {
		x.xxx_hidden_Type = nil
	}
}

const UserInputParameter_Type_not_set_case case_UserInputParameter_Type = 0
const UserInputParameter_Text_case case_UserInputParameter_Type = 100

func (x *UserInputParameter) WhichType() case_UserInputParameter_Type {
	if x == nil {
		return UserInputParameter_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *userInputParameter_Text_:
		return UserInputParameter_Text_case
	default:
		return UserInputParameter_Type_not_set_case
	}
}

type UserInputParameter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Display name presented to the user.
	Name string
	// Description of how the value is used within the recipe.
	Description string
	// Whether the parameter may be omitted by the user interface.
	Optional bool
	// Identifies the input widget or format expected for the parameter.

	// Fields of oneof xxx_hidden_Type:
	// Represents a multiline free-form text box.
	Text *UserInputParameter_Text
	// -- end of xxx_hidden_Type
}

func (b0 UserInputParameter_builder) Build() *UserInputParameter {
	m0 := &UserInputParameter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Optional = b.Optional
	if b.Text != nil {
		x.xxx_hidden_Type = &userInputParameter_Text_{b.Text}
	}
	return m0
}

type case_UserInputParameter_Type protoreflect.FieldNumber

func (x case_UserInputParameter_Type) String() string {
	md := file_osdd_common_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUserInputParameter_Type interface {
	isUserInputParameter_Type()
}

type userInputParameter_Text_ struct {
	// Represents a multiline free-form text box.
	Text *UserInputParameter_Text `protobuf:"bytes,100,opt,name=text,proto3,oneof"`
}

func (*userInputParameter_Text_) isUserInputParameter_Type() {}

// NameGenConfig configures automatic unique-name generation.
type NameGenConfig struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Len int32                  `protobuf:"varint,1,opt,name=len,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NameGenConfig) Reset() {
	*x = NameGenConfig{}
	mi := &file_osdd_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameGenConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameGenConfig) ProtoMessage() {}

func (x *NameGenConfig) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NameGenConfig) GetLen() int32 {
	if x != nil {
		return x.xxx_hidden_Len
	}
	return 0
}

func (x *NameGenConfig) SetLen(v int32) {
	x.xxx_hidden_Len = v
}

type NameGenConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Desired length of the generated identifier fragment.
	Len int32
}

func (b0 NameGenConfig_builder) Build() *NameGenConfig {
	m0 := &NameGenConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Len = b.Len
	return m0
}

// Exec describes a shell command invocation.
type Exec struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cmd  string                 `protobuf:"bytes,1,opt,name=cmd,proto3"`
	xxx_hidden_Args []string               `protobuf:"bytes,2,rep,name=args,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Exec) Reset() {
	*x = Exec{}
	mi := &file_osdd_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exec) ProtoMessage() {}

func (x *Exec) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Exec) GetCmd() string {
	if x != nil {
		return x.xxx_hidden_Cmd
	}
	return ""
}

func (x *Exec) GetArgs() []string {
	if x != nil {
		return x.xxx_hidden_Args
	}
	return nil
}

func (x *Exec) SetCmd(v string) {
	x.xxx_hidden_Cmd = v
}

func (x *Exec) SetArgs(v []string) {
	x.xxx_hidden_Args = v
}

type Exec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Executable or script to run.
	Cmd string
	// Command-line arguments passed in order.
	Args []string
}

func (b0 Exec_builder) Build() *Exec {
	m0 := &Exec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cmd = b.Cmd
	x.xxx_hidden_Args = b.Args
	return m0
}

// EntryFilter restricts a context entry to specific IDE integrations.
type EntryFilter struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ide []string               `protobuf:"bytes,1,rep,name=ide,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EntryFilter) Reset() {
	*x = EntryFilter{}
	mi := &file_osdd_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryFilter) ProtoMessage() {}

func (x *EntryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EntryFilter) GetIde() []string {
	if x != nil {
		return x.xxx_hidden_Ide
	}
	return nil
}

func (x *EntryFilter) SetIde(v []string) {
	x.xxx_hidden_Ide = v
}

type EntryFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// IDE identifiers (e.g., "claude", "codex") for which the entry is applicable.
	Ide []string
}

func (b0 EntryFilter_builder) Build() *EntryFilter {
	m0 := &EntryFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ide = b.Ide
	return m0
}

type DatesFilter struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_From *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3,oneof"`
	xxx_hidden_To   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3,oneof"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DatesFilter) Reset() {
	*x = DatesFilter{}
	mi := &file_osdd_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatesFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatesFilter) ProtoMessage() {}

func (x *DatesFilter) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DatesFilter) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *DatesFilter) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_To
	}
	return nil
}

func (x *DatesFilter) SetFrom(v *timestamppb.Timestamp) {
	x.xxx_hidden_From = v
}

func (x *DatesFilter) SetTo(v *timestamppb.Timestamp) {
	x.xxx_hidden_To = v
}

func (x *DatesFilter) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *DatesFilter) HasTo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_To != nil
}

func (x *DatesFilter) ClearFrom() {
	x.xxx_hidden_From = nil
}

func (x *DatesFilter) ClearTo() {
	x.xxx_hidden_To = nil
}

type DatesFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	From *timestamppb.Timestamp
	To   *timestamppb.Timestamp
}

func (b0 DatesFilter_builder) Build() *DatesFilter {
	m0 := &DatesFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_From = b.From
	x.xxx_hidden_To = b.To
	return m0
}

// Text indicates that the UI should prompt for free-form multi-line text.
type UserInputParameter_Text struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInputParameter_Text) Reset() {
	*x = UserInputParameter_Text{}
	mi := &file_osdd_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInputParameter_Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInputParameter_Text) ProtoMessage() {}

func (x *UserInputParameter_Text) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UserInputParameter_Text_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UserInputParameter_Text_builder) Build() *UserInputParameter_Text {
	m0 := &UserInputParameter_Text{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_osdd_common_proto protoreflect.FileDescriptor

const file_osdd_common_proto_rawDesc = "" +
	"\n" +
	"\x11osdd/common.proto\x12\vosdd.common\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n" +
	"\fGitReference\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x126\n" +
	"\aversion\x18\x02 \x01(\v2\x17.osdd.common.GitVersionH\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"\x91\x01\n" +
	"\rGitRepository\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x120\n" +
	"\x12auth_token_env_var\x18\x03 \x01(\tH\x00R\x0fauthTokenEnvVar\x88\x01\x01B\x15\n" +
	"\x13_auth_token_env_var\"B\n" +
	"\n" +
	"GitVersion\x12\x12\n" +
	"\x03tag\x18d \x01(\tH\x00R\x03tag\x12\x18\n" +
	"\x06commit\x18e \x01(\tH\x00R\x06commitB\x06\n" +
	"\x04type\"\xb2\x01\n" +
	"\x12UserInputParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\boptional\x18\x03 \x01(\bR\boptional\x12:\n" +
	"\x04text\x18d \x01(\v2$.osdd.common.UserInputParameter.TextH\x00R\x04text\x1a\x06\n" +
	"\x04TextB\x06\n" +
	"\x04type\"!\n" +
	"\rNameGenConfig\x12\x10\n" +
	"\x03len\x18\x01 \x01(\x05R\x03len\",\n" +
	"\x04Exec\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\x1f\n" +
	"\vEntryFilter\x12\x10\n" +
	"\x03ide\x18\x01 \x03(\tR\x03ide\"\x83\x01\n" +
	"\vDatesFilter\x123\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_toB-Z+github.com/opensdd/osdd-api/clients/go/osddb\x06proto3"

var file_osdd_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_osdd_common_proto_goTypes = []any{
	(*GitReference)(nil),            // 0: osdd.common.GitReference
	(*GitRepository)(nil),           // 1: osdd.common.GitRepository
	(*GitVersion)(nil),              // 2: osdd.common.GitVersion
	(*UserInputParameter)(nil),      // 3: osdd.common.UserInputParameter
	(*NameGenConfig)(nil),           // 4: osdd.common.NameGenConfig
	(*Exec)(nil),                    // 5: osdd.common.Exec
	(*EntryFilter)(nil),             // 6: osdd.common.EntryFilter
	(*DatesFilter)(nil),             // 7: osdd.common.DatesFilter
	(*UserInputParameter_Text)(nil), // 8: osdd.common.UserInputParameter.Text
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_osdd_common_proto_depIdxs = []int32{
	2, // 0: osdd.common.GitReference.version:type_name -> osdd.common.GitVersion
	8, // 1: osdd.common.UserInputParameter.text:type_name -> osdd.common.UserInputParameter.Text
	9, // 2: osdd.common.DatesFilter.from:type_name -> google.protobuf.Timestamp
	9, // 3: osdd.common.DatesFilter.to:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osdd_common_proto_init() }
func file_osdd_common_proto_init() {
	if File_osdd_common_proto != nil {
		return
	}
	file_osdd_common_proto_msgTypes[0].OneofWrappers = []any{}
	file_osdd_common_proto_msgTypes[1].OneofWrappers = []any{}
	file_osdd_common_proto_msgTypes[2].OneofWrappers = []any{
		(*gitVersion_Tag)(nil),
		(*gitVersion_Commit)(nil),
	}
	file_osdd_common_proto_msgTypes[3].OneofWrappers = []any{
		(*userInputParameter_Text_)(nil),
	}
	file_osdd_common_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osdd_common_proto_rawDesc), len(file_osdd_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osdd_common_proto_goTypes,
		DependencyIndexes: file_osdd_common_proto_depIdxs,
		MessageInfos:      file_osdd_common_proto_msgTypes,
	}.Build()
	File_osdd_common_proto = out.File
	file_osdd_common_proto_goTypes = nil
	file_osdd_common_proto_depIdxs = nil
}
