// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: osdd/content.proto

package osdd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Prefetch struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*PrefetchEntry      `protobuf:"bytes,1,rep,name=entries,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Prefetch) Reset() {
	*x = Prefetch{}
	mi := &file_osdd_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prefetch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prefetch) ProtoMessage() {}

func (x *Prefetch) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Prefetch) GetEntries() []*PrefetchEntry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *Prefetch) SetEntries(v []*PrefetchEntry) {
	x.xxx_hidden_Entries = &v
}

type Prefetch_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []*PrefetchEntry
}

func (b0 Prefetch_builder) Build() *Prefetch {
	m0 := &Prefetch{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type PrefetchEntry struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type isPrefetchEntry_Type   `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrefetchEntry) Reset() {
	*x = PrefetchEntry{}
	mi := &file_osdd_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefetchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchEntry) ProtoMessage() {}

func (x *PrefetchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrefetchEntry) GetCmd() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*prefetchEntry_Cmd); ok {
			return x.Cmd
		}
	}
	return ""
}

func (x *PrefetchEntry) SetCmd(v string) {
	x.xxx_hidden_Type = &prefetchEntry_Cmd{v}
}

func (x *PrefetchEntry) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *PrefetchEntry) HasCmd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*prefetchEntry_Cmd)
	return ok
}

func (x *PrefetchEntry) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *PrefetchEntry) ClearCmd() {
	if _, ok := x.xxx_hidden_Type.(*prefetchEntry_Cmd); ok {
		x.xxx_hidden_Type = nil
	}
}

const PrefetchEntry_Type_not_set_case case_PrefetchEntry_Type = 0
const PrefetchEntry_Cmd_case case_PrefetchEntry_Type = 100

func (x *PrefetchEntry) WhichType() case_PrefetchEntry_Type {
	if x == nil {
		return PrefetchEntry_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *prefetchEntry_Cmd:
		return PrefetchEntry_Cmd_case
	default:
		return PrefetchEntry_Type_not_set_case
	}
}

type PrefetchEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Type:
	Cmd *string
	// -- end of xxx_hidden_Type
}

func (b0 PrefetchEntry_builder) Build() *PrefetchEntry {
	m0 := &PrefetchEntry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cmd != nil {
		x.xxx_hidden_Type = &prefetchEntry_Cmd{*b.Cmd}
	}
	return m0
}

type case_PrefetchEntry_Type protoreflect.FieldNumber

func (x case_PrefetchEntry_Type) String() string {
	md := file_osdd_content_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPrefetchEntry_Type interface {
	isPrefetchEntry_Type()
}

type prefetchEntry_Cmd struct {
	Cmd string `protobuf:"bytes,100,opt,name=cmd,proto3,oneof"`
}

func (*prefetchEntry_Cmd) isPrefetchEntry_Type() {}

type PrefetchResult struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *[]*FetchedData        `protobuf:"bytes,1,rep,name=data,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrefetchResult) Reset() {
	*x = PrefetchResult{}
	mi := &file_osdd_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefetchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchResult) ProtoMessage() {}

func (x *PrefetchResult) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrefetchResult) GetData() []*FetchedData {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
	}
	return nil
}

func (x *PrefetchResult) SetData(v []*FetchedData) {
	x.xxx_hidden_Data = &v
}

type PrefetchResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []*FetchedData
}

func (b0 PrefetchResult_builder) Build() *PrefetchResult {
	m0 := &PrefetchResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = &b.Data
	return m0
}

type FetchedData struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id   string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Data string                 `protobuf:"bytes,2,opt,name=data,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchedData) Reset() {
	*x = FetchedData{}
	mi := &file_osdd_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchedData) ProtoMessage() {}

func (x *FetchedData) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FetchedData) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *FetchedData) GetData() string {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return ""
}

func (x *FetchedData) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *FetchedData) SetData(v string) {
	x.xxx_hidden_Data = v
}

type FetchedData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Data string
}

func (b0 FetchedData_builder) Build() *FetchedData {
	m0 := &FetchedData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Data = b.Data
	return m0
}

var File_osdd_content_proto protoreflect.FileDescriptor

const file_osdd_content_proto_rawDesc = "" +
	"\n" +
	"\x12osdd/content.proto\x12\fosdd.content\"A\n" +
	"\bPrefetch\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.osdd.content.PrefetchEntryR\aentries\"+\n" +
	"\rPrefetchEntry\x12\x12\n" +
	"\x03cmd\x18d \x01(\tH\x00R\x03cmdB\x06\n" +
	"\x04type\"?\n" +
	"\x0ePrefetchResult\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.osdd.content.FetchedDataR\x04data\"1\n" +
	"\vFetchedData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04dataB-Z+github.com/opensdd/osdd-api/clients/go/osddb\x06proto3"

var file_osdd_content_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_osdd_content_proto_goTypes = []any{
	(*Prefetch)(nil),       // 0: osdd.content.Prefetch
	(*PrefetchEntry)(nil),  // 1: osdd.content.PrefetchEntry
	(*PrefetchResult)(nil), // 2: osdd.content.PrefetchResult
	(*FetchedData)(nil),    // 3: osdd.content.FetchedData
}
var file_osdd_content_proto_depIdxs = []int32{
	1, // 0: osdd.content.Prefetch.entries:type_name -> osdd.content.PrefetchEntry
	3, // 1: osdd.content.PrefetchResult.data:type_name -> osdd.content.FetchedData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_osdd_content_proto_init() }
func file_osdd_content_proto_init() {
	if File_osdd_content_proto != nil {
		return
	}
	file_osdd_content_proto_msgTypes[1].OneofWrappers = []any{
		(*prefetchEntry_Cmd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osdd_content_proto_rawDesc), len(file_osdd_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osdd_content_proto_goTypes,
		DependencyIndexes: file_osdd_content_proto_depIdxs,
		MessageInfos:      file_osdd_content_proto_msgTypes,
	}.Build()
	File_osdd_content_proto = out.File
	file_osdd_content_proto_goTypes = nil
	file_osdd_content_proto_depIdxs = nil
}
