// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: osdd/materialized.proto

package osdd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaterializedResult struct {
	state              protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*MaterializedResult_Entry `protobuf:"bytes,1,rep,name=entries,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MaterializedResult) Reset() {
	*x = MaterializedResult{}
	mi := &file_osdd_materialized_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedResult) ProtoMessage() {}

func (x *MaterializedResult) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_materialized_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MaterializedResult) GetEntries() []*MaterializedResult_Entry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *MaterializedResult) SetEntries(v []*MaterializedResult_Entry) {
	x.xxx_hidden_Entries = &v
}

type MaterializedResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []*MaterializedResult_Entry
}

func (b0 MaterializedResult_builder) Build() *MaterializedResult {
	m0 := &MaterializedResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type FullFileContent struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path    string                 `protobuf:"bytes,1,opt,name=path,proto3"`
	xxx_hidden_Content string                 `protobuf:"bytes,2,opt,name=content,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FullFileContent) Reset() {
	*x = FullFileContent{}
	mi := &file_osdd_materialized_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullFileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullFileContent) ProtoMessage() {}

func (x *FullFileContent) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_materialized_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FullFileContent) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *FullFileContent) GetContent() string {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return ""
}

func (x *FullFileContent) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *FullFileContent) SetContent(v string) {
	x.xxx_hidden_Content = v
}

type FullFileContent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path    string
	Content string
}

func (b0 FullFileContent_builder) Build() *FullFileContent {
	m0 := &FullFileContent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_Content = b.Content
	return m0
}

type MaterializedResult_Entry struct {
	state           protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Type isMaterializedResult_Entry_Type `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MaterializedResult_Entry) Reset() {
	*x = MaterializedResult_Entry{}
	mi := &file_osdd_materialized_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedResult_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedResult_Entry) ProtoMessage() {}

func (x *MaterializedResult_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_osdd_materialized_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MaterializedResult_Entry) GetFile() *FullFileContent {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*materializedResult_Entry_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *MaterializedResult_Entry) GetDirectory() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*materializedResult_Entry_Directory); ok {
			return x.Directory
		}
	}
	return ""
}

func (x *MaterializedResult_Entry) SetFile(v *FullFileContent) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &materializedResult_Entry_File{v}
}

func (x *MaterializedResult_Entry) SetDirectory(v string) {
	x.xxx_hidden_Type = &materializedResult_Entry_Directory{v}
}

func (x *MaterializedResult_Entry) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *MaterializedResult_Entry) HasFile() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*materializedResult_Entry_File)
	return ok
}

func (x *MaterializedResult_Entry) HasDirectory() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*materializedResult_Entry_Directory)
	return ok
}

func (x *MaterializedResult_Entry) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *MaterializedResult_Entry) ClearFile() {
	if _, ok := x.xxx_hidden_Type.(*materializedResult_Entry_File); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *MaterializedResult_Entry) ClearDirectory() {
	if _, ok := x.xxx_hidden_Type.(*materializedResult_Entry_Directory); ok {
		x.xxx_hidden_Type = nil
	}
}

const MaterializedResult_Entry_Type_not_set_case case_MaterializedResult_Entry_Type = 0
const MaterializedResult_Entry_File_case case_MaterializedResult_Entry_Type = 100
const MaterializedResult_Entry_Directory_case case_MaterializedResult_Entry_Type = 101

func (x *MaterializedResult_Entry) WhichType() case_MaterializedResult_Entry_Type {
	if x == nil {
		return MaterializedResult_Entry_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *materializedResult_Entry_File:
		return MaterializedResult_Entry_File_case
	case *materializedResult_Entry_Directory:
		return MaterializedResult_Entry_Directory_case
	default:
		return MaterializedResult_Entry_Type_not_set_case
	}
}

type MaterializedResult_Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Type:
	File      *FullFileContent
	Directory *string
	// -- end of xxx_hidden_Type
}

func (b0 MaterializedResult_Entry_builder) Build() *MaterializedResult_Entry {
	m0 := &MaterializedResult_Entry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.File != nil {
		x.xxx_hidden_Type = &materializedResult_Entry_File{b.File}
	}
	if b.Directory != nil {
		x.xxx_hidden_Type = &materializedResult_Entry_Directory{*b.Directory}
	}
	return m0
}

type case_MaterializedResult_Entry_Type protoreflect.FieldNumber

func (x case_MaterializedResult_Entry_Type) String() string {
	md := file_osdd_materialized_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isMaterializedResult_Entry_Type interface {
	isMaterializedResult_Entry_Type()
}

type materializedResult_Entry_File struct {
	File *FullFileContent `protobuf:"bytes,100,opt,name=file,proto3,oneof"`
}

type materializedResult_Entry_Directory struct {
	Directory string `protobuf:"bytes,101,opt,name=directory,proto3,oneof"`
}

func (*materializedResult_Entry_File) isMaterializedResult_Entry_Type() {}

func (*materializedResult_Entry_Directory) isMaterializedResult_Entry_Type() {}

var File_osdd_materialized_proto protoreflect.FileDescriptor

const file_osdd_materialized_proto_rawDesc = "" +
	"\n" +
	"\x17osdd/materialized.proto\x12\x11osdd.materialized\"\xc6\x01\n" +
	"\x12MaterializedResult\x12E\n" +
	"\aentries\x18\x01 \x03(\v2+.osdd.materialized.MaterializedResult.EntryR\aentries\x1ai\n" +
	"\x05Entry\x128\n" +
	"\x04file\x18d \x01(\v2\".osdd.materialized.FullFileContentH\x00R\x04file\x12\x1e\n" +
	"\tdirectory\x18e \x01(\tH\x00R\tdirectoryB\x06\n" +
	"\x04type\"?\n" +
	"\x0fFullFileContent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontentB-Z+github.com/opensdd/osdd-api/clients/go/osddb\x06proto3"

var file_osdd_materialized_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osdd_materialized_proto_goTypes = []any{
	(*MaterializedResult)(nil),       // 0: osdd.materialized.MaterializedResult
	(*FullFileContent)(nil),          // 1: osdd.materialized.FullFileContent
	(*MaterializedResult_Entry)(nil), // 2: osdd.materialized.MaterializedResult.Entry
}
var file_osdd_materialized_proto_depIdxs = []int32{
	2, // 0: osdd.materialized.MaterializedResult.entries:type_name -> osdd.materialized.MaterializedResult.Entry
	1, // 1: osdd.materialized.MaterializedResult.Entry.file:type_name -> osdd.materialized.FullFileContent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_osdd_materialized_proto_init() }
func file_osdd_materialized_proto_init() {
	if File_osdd_materialized_proto != nil {
		return
	}
	file_osdd_materialized_proto_msgTypes[2].OneofWrappers = []any{
		(*materializedResult_Entry_File)(nil),
		(*materializedResult_Entry_Directory)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osdd_materialized_proto_rawDesc), len(file_osdd_materialized_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osdd_materialized_proto_goTypes,
		DependencyIndexes: file_osdd_materialized_proto_depIdxs,
		MessageInfos:      file_osdd_materialized_proto_msgTypes,
	}.Build()
	File_osdd_materialized_proto = out.File
	file_osdd_materialized_proto_goTypes = nil
	file_osdd_materialized_proto_depIdxs = nil
}
