// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.1
//   protoc               v5.29.3
// source: osdd/recipes/recipe.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Prefetch } from "../content";
import { Context } from "./context";
import { Ide } from "./ide";

export const protobufPackage = "osdd.recipes.recipe";

export interface Recipe {
  prefetch?: Prefetch | undefined;
  context?: Context | undefined;
  ide?: Ide | undefined;
}

export interface ExecutableRecipe {
  recipe: Recipe | undefined;
  entryPoint: EntryPoint | undefined;
}

export interface EntryPoint {
  ideType: string;
}

function createBaseRecipe(): Recipe {
  return { prefetch: undefined, context: undefined, ide: undefined };
}

export const Recipe: MessageFns<Recipe> = {
  encode(message: Recipe, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.prefetch !== undefined) {
      Prefetch.encode(message.prefetch, writer.uint32(10).fork()).join();
    }
    if (message.context !== undefined) {
      Context.encode(message.context, writer.uint32(18).fork()).join();
    }
    if (message.ide !== undefined) {
      Ide.encode(message.ide, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Recipe {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecipe();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.prefetch = Prefetch.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.context = Context.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ide = Ide.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Recipe {
    return {
      prefetch: isSet(object.prefetch) ? Prefetch.fromJSON(object.prefetch) : undefined,
      context: isSet(object.context) ? Context.fromJSON(object.context) : undefined,
      ide: isSet(object.ide) ? Ide.fromJSON(object.ide) : undefined,
    };
  },

  toJSON(message: Recipe): unknown {
    const obj: any = {};
    if (message.prefetch !== undefined) {
      obj.prefetch = Prefetch.toJSON(message.prefetch);
    }
    if (message.context !== undefined) {
      obj.context = Context.toJSON(message.context);
    }
    if (message.ide !== undefined) {
      obj.ide = Ide.toJSON(message.ide);
    }
    return obj;
  },

  create(base?: DeepPartial<Recipe>): Recipe {
    return Recipe.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Recipe>): Recipe {
    const message = createBaseRecipe();
    message.prefetch = (object.prefetch !== undefined && object.prefetch !== null)
      ? Prefetch.fromPartial(object.prefetch)
      : undefined;
    message.context = (object.context !== undefined && object.context !== null)
      ? Context.fromPartial(object.context)
      : undefined;
    message.ide = (object.ide !== undefined && object.ide !== null) ? Ide.fromPartial(object.ide) : undefined;
    return message;
  },
};

function createBaseExecutableRecipe(): ExecutableRecipe {
  return { recipe: undefined, entryPoint: undefined };
}

export const ExecutableRecipe: MessageFns<ExecutableRecipe> = {
  encode(message: ExecutableRecipe, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.recipe !== undefined) {
      Recipe.encode(message.recipe, writer.uint32(10).fork()).join();
    }
    if (message.entryPoint !== undefined) {
      EntryPoint.encode(message.entryPoint, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecutableRecipe {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecutableRecipe();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.recipe = Recipe.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entryPoint = EntryPoint.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecutableRecipe {
    return {
      recipe: isSet(object.recipe) ? Recipe.fromJSON(object.recipe) : undefined,
      entryPoint: isSet(object.entryPoint) ? EntryPoint.fromJSON(object.entryPoint) : undefined,
    };
  },

  toJSON(message: ExecutableRecipe): unknown {
    const obj: any = {};
    if (message.recipe !== undefined) {
      obj.recipe = Recipe.toJSON(message.recipe);
    }
    if (message.entryPoint !== undefined) {
      obj.entryPoint = EntryPoint.toJSON(message.entryPoint);
    }
    return obj;
  },

  create(base?: DeepPartial<ExecutableRecipe>): ExecutableRecipe {
    return ExecutableRecipe.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ExecutableRecipe>): ExecutableRecipe {
    const message = createBaseExecutableRecipe();
    message.recipe = (object.recipe !== undefined && object.recipe !== null)
      ? Recipe.fromPartial(object.recipe)
      : undefined;
    message.entryPoint = (object.entryPoint !== undefined && object.entryPoint !== null)
      ? EntryPoint.fromPartial(object.entryPoint)
      : undefined;
    return message;
  },
};

function createBaseEntryPoint(): EntryPoint {
  return { ideType: "" };
}

export const EntryPoint: MessageFns<EntryPoint> = {
  encode(message: EntryPoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ideType !== "") {
      writer.uint32(10).string(message.ideType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntryPoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntryPoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ideType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EntryPoint {
    return { ideType: isSet(object.ideType) ? gt.String(object.ideType) : "" };
  },

  toJSON(message: EntryPoint): unknown {
    const obj: any = {};
    if (message.ideType !== "") {
      obj.ideType = message.ideType;
    }
    return obj;
  },

  create(base?: DeepPartial<EntryPoint>): EntryPoint {
    return EntryPoint.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EntryPoint>): EntryPoint {
    const message = createBaseEntryPoint();
    message.ideType = object.ideType ?? "";
    return message;
  },
};

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
