// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: osdd/common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "osdd.common";

/** GitReference identifies a file or directory stored in a Git repository. */
export interface GitReference {
  /** Relative path within the repository that should be fetched. */
  path: string;
  /** Optional revision selector (tag or commit SHA) to pin the lookup. */
  version?: GitVersion | undefined;
}

export interface GitRepository {
  /** Full name of the repository in the format "owner/name". */
  fullName: string;
  /** Supported github, bitbucket. */
  provider: string;
  /** Name of the env var containing auth token for the repository. May be empty, then no token is used. */
  authTokenEnvVar?: string | undefined;
}

/** GitVersion specifies the exact revision to use for a Git reference. */
export interface GitVersion {
  /** Type of revision identifier supplied by the recipe. */
  type?:
    | //
    /** Named Git tag such as v1.2.3. */
    { $case: "tag"; value: string }
    | //
    /** Commit SHA (full or abbreviated). */
    { $case: "commit"; value: string }
    | undefined;
}

/** UserInputParameter declares a parameter collected from the end user. */
export interface UserInputParameter {
  /** Display name presented to the user. */
  name: string;
  /** Description of how the value is used within the recipe. */
  description: string;
  /** Whether the parameter may be omitted by the user interface. */
  optional: boolean;
  /** Identifies the input widget or format expected for the parameter. */
  type?:
    | //
    /** Represents a multiline free-form text box. */
    { $case: "text"; value: UserInputParameter_Text }
    | undefined;
}

/** Text indicates that the UI should prompt for free-form multi-line text. */
export interface UserInputParameter_Text {
}

/** NameGenConfig configures automatic unique-name generation. */
export interface NameGenConfig {
  /** Desired length of the generated identifier fragment. */
  len: number;
}

/** Exec describes a shell command invocation. */
export interface Exec {
  /** Executable or script to run. */
  cmd: string;
  /** Command-line arguments passed in order. */
  args: string[];
}

/** EntryFilter restricts a context entry to specific IDE integrations. */
export interface EntryFilter {
  /** IDE identifiers (e.g., "claude", "codex") for which the entry is applicable. */
  ide: string[];
}

function createBaseGitReference(): GitReference {
  return { path: "", version: undefined };
}

export const GitReference: MessageFns<GitReference> = {
  encode(message: GitReference, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    if (message.version !== undefined) {
      GitVersion.encode(message.version, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitReference {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitReference();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.version = GitVersion.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitReference {
    return {
      path: isSet(object.path) ? gt.String(object.path) : "",
      version: isSet(object.version) ? GitVersion.fromJSON(object.version) : undefined,
    };
  },

  toJSON(message: GitReference): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.version !== undefined) {
      obj.version = GitVersion.toJSON(message.version);
    }
    return obj;
  },

  create(base?: DeepPartial<GitReference>): GitReference {
    return GitReference.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GitReference>): GitReference {
    const message = createBaseGitReference();
    message.path = object.path ?? "";
    message.version = (object.version !== undefined && object.version !== null)
      ? GitVersion.fromPartial(object.version)
      : undefined;
    return message;
  },
};

function createBaseGitRepository(): GitRepository {
  return { fullName: "", provider: "", authTokenEnvVar: undefined };
}

export const GitRepository: MessageFns<GitRepository> = {
  encode(message: GitRepository, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fullName !== "") {
      writer.uint32(10).string(message.fullName);
    }
    if (message.provider !== "") {
      writer.uint32(18).string(message.provider);
    }
    if (message.authTokenEnvVar !== undefined) {
      writer.uint32(26).string(message.authTokenEnvVar);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitRepository {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitRepository();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fullName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.authTokenEnvVar = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitRepository {
    return {
      fullName: isSet(object.fullName) ? gt.String(object.fullName) : "",
      provider: isSet(object.provider) ? gt.String(object.provider) : "",
      authTokenEnvVar: isSet(object.authTokenEnvVar) ? gt.String(object.authTokenEnvVar) : undefined,
    };
  },

  toJSON(message: GitRepository): unknown {
    const obj: any = {};
    if (message.fullName !== "") {
      obj.fullName = message.fullName;
    }
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.authTokenEnvVar !== undefined) {
      obj.authTokenEnvVar = message.authTokenEnvVar;
    }
    return obj;
  },

  create(base?: DeepPartial<GitRepository>): GitRepository {
    return GitRepository.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GitRepository>): GitRepository {
    const message = createBaseGitRepository();
    message.fullName = object.fullName ?? "";
    message.provider = object.provider ?? "";
    message.authTokenEnvVar = object.authTokenEnvVar ?? undefined;
    return message;
  },
};

function createBaseGitVersion(): GitVersion {
  return { type: undefined };
}

export const GitVersion: MessageFns<GitVersion> = {
  encode(message: GitVersion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.type?.$case) {
      case "tag":
        writer.uint32(802).string(message.type.value);
        break;
      case "commit":
        writer.uint32(810).string(message.type.value);
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitVersion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitVersion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 100: {
          if (tag !== 802) {
            break;
          }

          message.type = { $case: "tag", value: reader.string() };
          continue;
        }
        case 101: {
          if (tag !== 810) {
            break;
          }

          message.type = { $case: "commit", value: reader.string() };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitVersion {
    return {
      type: isSet(object.tag)
        ? { $case: "tag", value: gt.String(object.tag) }
        : isSet(object.commit)
        ? { $case: "commit", value: gt.String(object.commit) }
        : undefined,
    };
  },

  toJSON(message: GitVersion): unknown {
    const obj: any = {};
    if (message.type?.$case === "tag") {
      obj.tag = message.type.value;
    } else if (message.type?.$case === "commit") {
      obj.commit = message.type.value;
    }
    return obj;
  },

  create(base?: DeepPartial<GitVersion>): GitVersion {
    return GitVersion.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GitVersion>): GitVersion {
    const message = createBaseGitVersion();
    switch (object.type?.$case) {
      case "tag": {
        if (object.type?.value !== undefined && object.type?.value !== null) {
          message.type = { $case: "tag", value: object.type.value };
        }
        break;
      }
      case "commit": {
        if (object.type?.value !== undefined && object.type?.value !== null) {
          message.type = { $case: "commit", value: object.type.value };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseUserInputParameter(): UserInputParameter {
  return { name: "", description: "", optional: false, type: undefined };
}

export const UserInputParameter: MessageFns<UserInputParameter> = {
  encode(message: UserInputParameter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.optional !== false) {
      writer.uint32(24).bool(message.optional);
    }
    switch (message.type?.$case) {
      case "text":
        UserInputParameter_Text.encode(message.type.value, writer.uint32(802).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserInputParameter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserInputParameter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.optional = reader.bool();
          continue;
        }
        case 100: {
          if (tag !== 802) {
            break;
          }

          message.type = { $case: "text", value: UserInputParameter_Text.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserInputParameter {
    return {
      name: isSet(object.name) ? gt.String(object.name) : "",
      description: isSet(object.description) ? gt.String(object.description) : "",
      optional: isSet(object.optional) ? gt.Boolean(object.optional) : false,
      type: isSet(object.text) ? { $case: "text", value: UserInputParameter_Text.fromJSON(object.text) } : undefined,
    };
  },

  toJSON(message: UserInputParameter): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.optional !== false) {
      obj.optional = message.optional;
    }
    if (message.type?.$case === "text") {
      obj.text = UserInputParameter_Text.toJSON(message.type.value);
    }
    return obj;
  },

  create(base?: DeepPartial<UserInputParameter>): UserInputParameter {
    return UserInputParameter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserInputParameter>): UserInputParameter {
    const message = createBaseUserInputParameter();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.optional = object.optional ?? false;
    switch (object.type?.$case) {
      case "text": {
        if (object.type?.value !== undefined && object.type?.value !== null) {
          message.type = { $case: "text", value: UserInputParameter_Text.fromPartial(object.type.value) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseUserInputParameter_Text(): UserInputParameter_Text {
  return {};
}

export const UserInputParameter_Text: MessageFns<UserInputParameter_Text> = {
  encode(_: UserInputParameter_Text, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserInputParameter_Text {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserInputParameter_Text();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): UserInputParameter_Text {
    return {};
  },

  toJSON(_: UserInputParameter_Text): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<UserInputParameter_Text>): UserInputParameter_Text {
    return UserInputParameter_Text.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<UserInputParameter_Text>): UserInputParameter_Text {
    const message = createBaseUserInputParameter_Text();
    return message;
  },
};

function createBaseNameGenConfig(): NameGenConfig {
  return { len: 0 };
}

export const NameGenConfig: MessageFns<NameGenConfig> = {
  encode(message: NameGenConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.len !== 0) {
      writer.uint32(8).int32(message.len);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NameGenConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNameGenConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.len = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NameGenConfig {
    return { len: isSet(object.len) ? gt.Number(object.len) : 0 };
  },

  toJSON(message: NameGenConfig): unknown {
    const obj: any = {};
    if (message.len !== 0) {
      obj.len = Math.round(message.len);
    }
    return obj;
  },

  create(base?: DeepPartial<NameGenConfig>): NameGenConfig {
    return NameGenConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NameGenConfig>): NameGenConfig {
    const message = createBaseNameGenConfig();
    message.len = object.len ?? 0;
    return message;
  },
};

function createBaseExec(): Exec {
  return { cmd: "", args: [] };
}

export const Exec: MessageFns<Exec> = {
  encode(message: Exec, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cmd !== "") {
      writer.uint32(10).string(message.cmd);
    }
    for (const v of message.args) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Exec {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExec();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cmd = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.args.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Exec {
    return {
      cmd: isSet(object.cmd) ? gt.String(object.cmd) : "",
      args: gt.Array.isArray(object?.args) ? object.args.map((e: any) => gt.String(e)) : [],
    };
  },

  toJSON(message: Exec): unknown {
    const obj: any = {};
    if (message.cmd !== "") {
      obj.cmd = message.cmd;
    }
    if (message.args?.length) {
      obj.args = message.args;
    }
    return obj;
  },

  create(base?: DeepPartial<Exec>): Exec {
    return Exec.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Exec>): Exec {
    const message = createBaseExec();
    message.cmd = object.cmd ?? "";
    message.args = object.args?.map((e) => e) || [];
    return message;
  },
};

function createBaseEntryFilter(): EntryFilter {
  return { ide: [] };
}

export const EntryFilter: MessageFns<EntryFilter> = {
  encode(message: EntryFilter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ide) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntryFilter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntryFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ide.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EntryFilter {
    return { ide: gt.Array.isArray(object?.ide) ? object.ide.map((e: any) => gt.String(e)) : [] };
  },

  toJSON(message: EntryFilter): unknown {
    const obj: any = {};
    if (message.ide?.length) {
      obj.ide = message.ide;
    }
    return obj;
  },

  create(base?: DeepPartial<EntryFilter>): EntryFilter {
    return EntryFilter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EntryFilter>): EntryFilter {
    const message = createBaseEntryFilter();
    message.ide = object.ide?.map((e) => e) || [];
    return message;
  },
};

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
